In [1]:
import numpy as np

In [6]:
arr1 =np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))
arr2



array([[2, 2, 1],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [7]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 2]], dtype=int32)

In [9]:
# makes the array in one dimension's
arr1.flatten()

array([1, 1, 2, 2, 1, 2, 2, 1, 2], dtype=int32)

In [10]:
#expand dimensions
arr2=np.array([1,2,3,4])

In [13]:
# expand dimensions
np.expand_dims(arr1,axis=1)

array([[[1, 1, 2]],

       [[2, 1, 2]],

       [[2, 1, 2]]], dtype=int32)