In [2]:
import numpy as np


In [4]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [3]:
a.ndim

1

# Using the dimensions

In [6]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
b=np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [11]:
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
arrx=np.zeros((3,8))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros((1,2,2,3,4))

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [ ]:
arr=np.zeros((3,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
a=arr+5
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

# Empty array


In [21]:
np.empty((3,4))

array([[1.29545002e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11260619e-306, 1.58817677e-052, 4.46630576e-090,
        7.92560559e+165],
       [2.83028655e-033, 1.79081682e+160, 3.99910963e+252,
        4.93432906e+257]])

In [14]:
import random
random.choice((1,2,34,5,7))

1

In [22]:
arrz=np.empty((3,4))
print(arrz)

[[1.29545002e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [1.11260619e-306 1.58817677e-052 4.46630576e-090 7.92560559e+165]
 [2.83028655e-033 1.79081682e+160 3.99910963e+252 4.93432906e+257]]


In [19]:
import numpy as np

# Create a 3x4 empty array
array = np.empty((3, 4))
print(array)

[[6.95182710e-310 1.29545168e-311 0.00000000e+000 1.29545168e-311]
 [6.45268351e+155 1.29545168e-311 1.31267430e-071 0.00000000e+000]
 [1.29545168e-311 1.29545168e-311 1.29545168e-311 0.00000000e+000]]


In [28]:
np.random.random_sample([3,5])

array([[0.46953099, 0.43224609, 0.12727821, 0.73508813, 0.2289212 ],
       [0.45670798, 0.7272893 , 0.1643288 , 0.44826675, 0.80826881],
       [0.9301999 , 0.97184482, 0.21728873, 0.56557656, 0.97210183]])

In [29]:
np.random.rand(2,3)

array([[0.62864217, 0.14401332, 0.99107103],
       [0.76368004, 0.00518295, 0.45365117]])

# Standard normal distribution

In [30]:
np.random.rand(2,3)

array([[0.11369887, 0.32357661, 0.04399654],
       [0.28392999, 0.96783298, 0.83309095]])

In [33]:
np.random.randint(1,4,size=(3,4))

array([[2, 3, 2, 2],
       [3, 3, 2, 1],
       [1, 2, 3, 3]], dtype=int32)

# Reshaping the array

In [35]:
arr=np.zeros((3,5))

In [36]:
arr+5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [37]:
myarrz=np.random.randint(1,5,size=(3,4))

In [39]:
trr=np.random.randint(1,5,size=(3,4))

In [40]:
trr.ndim

2

In [41]:
trr.shape

(3, 4)

In [42]:
trr.size

12

# Reshaping the arrays


In [48]:
mytr=np.array((1,2,3,4,5,6,7,8))
mytr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
mytr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])