In [3]:
import numpy as np

In [4]:
arr1 =np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))
arr2



array([[1, 2, 1],
       [2, 2, 1],
       [1, 1, 1]], dtype=int32)

In [7]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 2]], dtype=int32)

In [9]:
# makes the array in one dimension's
arr1.flatten()

array([1, 1, 2, 2, 1, 2, 2, 1, 2], dtype=int32)

In [10]:
#expand dimensions
arr2=np.array([1,2,3,4])

In [13]:
# expand dimensions
np.expand_dims(arr1,axis=1)

array([[[1, 1, 2]],

       [[2, 1, 2]],

       [[2, 1, 2]]], dtype=int32)

In [6]:
# Squeezing the dimensions 1
np.squeeze(arr1)

array([[1, 1, 1],
       [2, 1, 2],
       [2, 1, 1]], dtype=int32)

In [7]:
arr1

array([[1, 1, 1],
       [2, 1, 2],
       [2, 1, 1]], dtype=int32)

In [8]:
# repeating the coloumns wise

np.repeat(arr1,3,axis=0)




array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 1, 2],
       [2, 1, 2],
       [2, 1, 2],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 1]], dtype=int32)

In [9]:
c=np.array([[1,2],[3,4],[5,7],[78,12]])
c

array([[ 1,  2],
       [ 3,  4],
       [ 5,  7],
       [78, 12]])

In [ ]:
# shift the rows downward to upward
np.roll(c,2)

array([[78, 12],
       [ 1,  2],
       [ 3,  4],
       [ 5,  7]])

In [11]:
# using arr1 & 2
arr1*2

array([[2, 2, 2],
       [4, 2, 4],
       [4, 2, 2]], dtype=int32)

In [12]:
d=np.array(["pw","Skills","will"])
d

array(['pw', 'Skills', 'will'], dtype='<U6')

In [13]:
np.char.upper(d)

array(['PW', 'SKILLS', 'WILL'], dtype='<U6')

In [14]:
np.char.capitalize(d)

array(['Pw', 'Skills', 'Will'], dtype='<U6')

In [15]:
# having the mathematical functions
arr1

array([[1, 1, 1],
       [2, 1, 2],
       [2, 1, 1]], dtype=int32)

In [16]:
np.sin(arr1)

array([[0.84147098, 0.84147098, 0.84147098],
       [0.90929743, 0.84147098, 0.90929743],
       [0.90929743, 0.84147098, 0.84147098]])

In [17]:
np.tan(arr1)

array([[ 1.55740772,  1.55740772,  1.55740772],
       [-2.18503986,  1.55740772, -2.18503986],
       [-2.18503986,  1.55740772,  1.55740772]])

In [18]:
np.log10(arr1)

array([[0.     , 0.     , 0.     ],
       [0.30103, 0.     , 0.30103],
       [0.30103, 0.     , 0.     ]])

In [19]:
np.exp(arr1)

array([[2.71828183, 2.71828183, 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183]])

In [20]:
np.power(arr1,3)

array([[1, 1, 1],
       [8, 1, 8],
       [8, 1, 1]], dtype=int32)

In [21]:
np.max(arr1)

np.int32(2)

In [22]:
np.mean(arr1)

np.float64(1.3333333333333333)

In [23]:
np.std(arr1)

np.float64(0.4714045207910317)

In [24]:
np.var(arr1)

np.float64(0.2222222222222222)

In [25]:
arr1-arr2

array([[ 0, -1,  0],
       [ 0, -1,  1],
       [ 1,  0,  0]], dtype=int32)

In [26]:
np.subtract(arr1,arr2)

array([[ 0, -1,  0],
       [ 0, -1,  1],
       [ 1,  0,  0]], dtype=int32)

In [27]:
np.multiply(arr2,arr1)

array([[1, 2, 1],
       [4, 2, 2],
       [2, 1, 1]], dtype=int32)

In [28]:
np.mod(arr1,arr2)

array([[0, 1, 0],
       [0, 1, 0],
       [0, 0, 0]], dtype=int32)

In [29]:
np.sqrt(arr2)

array([[1.        , 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.        ],
       [1.        , 1.        , 1.        ]])