# Numpy , Pandas, Matpotlib & seaborn & ploty & Boken

In [2]:
# Numpy 1
import numpy as np

In [3]:
np.__version__

'2.2.2'

In [4]:
list_data=[1,2,3,4,5,6,7,8,"muthuswz",1.2]
list_data

[1, 2, 3, 4, 5, 6, 7, 8, 'muthuswz', 1.2]

In [6]:
# converting inot arra
myarr=np.array(list_data)
myarr

array(['1', '2', '3', '4', '5', '6', '7', '8', 'muthuswz', '1.2'],
      dtype='<U32')

In [8]:
type(myarr)

numpy.ndarray

In [10]:
# Making the 2 dimension array in numpy
myarr1=np.array([[1,2,3,4,5],[4,5,6,7,5]])
myarr1

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 5]])

In [11]:
type(myarr1)

numpy.ndarray

In [13]:
# creating the matrix in python numpy
mat=np.matrix([1,2,3,4,5])
mat

matrix([[1, 2, 3, 4, 5]])

In [15]:
#creating the 2 dimension matrix
ap1=np.matrix([[1,2,3,4,6],[1,2,3,4,5]])
ap1

matrix([[1, 2, 3, 4, 6],
        [1, 2, 3, 4, 5]])

In [16]:
ap2=np.matrix([[1,2,3,4,6],[1,2,3,4,5],[1,2,3,4,7]])
ap2

matrix([[1, 2, 3, 4, 6],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 7]])

In [18]:
type(ap2)

numpy.matrix

In [ ]:
# Converting to an array
