# Numpy , Pandas, Matpotlib & seaborn & ploty & Boken

In [2]:
# Numpy 1
import numpy as np

In [3]:
np.__version__

'2.2.2'

In [4]:
list_data=[1,2,3,4,5,6,7,8,"muthuswz",1.2]
list_data

[1, 2, 3, 4, 5, 6, 7, 8, 'muthuswz', 1.2]

In [6]:
# converting inot arra
myarr=np.array(list_data)
myarr

array(['1', '2', '3', '4', '5', '6', '7', '8', 'muthuswz', '1.2'],
      dtype='<U32')

In [8]:
type(myarr)

numpy.ndarray

In [10]:
# Making the 2 dimension array in numpy
myarr1=np.array([[1,2,3,4,5],[4,5,6,7,5]])
myarr1

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 5]])

In [11]:
type(myarr1)

numpy.ndarray

In [13]:
# creating the matrix in python numpy
mat=np.matrix([1,2,3,4,5])
mat

matrix([[1, 2, 3, 4, 5]])

In [15]:
#creating the 2 dimension matrix
ap1=np.matrix([[1,2,3,4,6],[1,2,3,4,5]])
ap1

matrix([[1, 2, 3, 4, 6],
        [1, 2, 3, 4, 5]])

In [16]:
ap2=np.matrix([[1,2,3,4,6],[1,2,3,4,5],[1,2,3,4,7]])
ap2

matrix([[1, 2, 3, 4, 6],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 7]])

In [18]:
type(ap2)

numpy.matrix

In [21]:
# Converting to an array
mt=[1,2,3,4,6,6]
z=np.asarray(mt)

In [22]:
type(z)

numpy.ndarray

In [23]:
# using the lambda
np.fromfunction(lambda i,j: i==j,(3,3))


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
arr1=np.fromfunction(lambda i,j: i==j,(3,3))
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [3]:
# Converting to an array 
am=[1,2,3,4]
np.asarray(am)

array([1, 2, 3, 4])

In [4]:
np.asanyarray([1,2,3,4])


array([1, 2, 3, 4])

In [5]:
# Converting the tuple into array
t=([1,2,3,4],[4,5,6,7])
type(t)

tuple

In [6]:
np.array(t)

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [9]:
#array is mutuable
mytrr=[10,200,30,40,60,90,599]
mytrr[0]=1000
mytrr

[1000, 200, 30, 40, 60, 90, 599]

In [14]:
a=mytrr
a

[1000, 200, 30, 40, 60, 90, 599]

In [16]:
#copying array without changing 
b=a.copy()
b

[1000, 200, 30, 40, 60, 90, 599]

In [17]:
np.fromfunction(lambda i,j: i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [18]:
arr2=np.fromfunction(lambda i, j: i==j,(4,4))
arr2

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [24]:
arr2.ndim

2

In [25]:
# True & False 

In [26]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])