In [1]:
import numpy as np

In [2]:
arrm1=np.random.randint(1,3,(3,3))
arrm2=np.random.randint(1,3,(3,3))


In [3]:
arrm1

array([[2, 2, 1],
       [1, 1, 2],
       [1, 2, 1]], dtype=int32)

In [5]:
arrm2

array([[2, 1, 1],
       [1, 2, 1],
       [2, 1, 1]], dtype=int32)

In [6]:
arrm2+arrm1

array([[4, 3, 2],
       [2, 3, 3],
       [3, 3, 2]], dtype=int32)