In [1]:
import numpy as np

In [2]:
a=np.zeros(5)

In [3]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [7]:
# adding the  row & coloumns
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# using the ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#using the arrray's

np.array([[1,2,2,2,2,],[3,3,3,3,3],[1,2,3,4,5]])


array([[1, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [1, 2, 3, 4, 5]])

In [ ]:
# added the four arrays
# first no. of array & second rows & third columns
# first defines the dimensions of the arrays
np.zeros((4,2,14))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [22]:
mn=np.zeros((1,1,3,3))
mn

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [23]:
tmz=np.zeros((1,2,3,4,5,6))
tmz

array([[[[[[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]]],


         [[[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0.

In [31]:
# mulitiplying the array
a=np.ones((8,1,5))
a+100

array([[[101., 101., 101., 101., 101.]],

       [[101., 101., 101., 101., 101.]],

       [[101., 101., 101., 101., 101.]],

       [[101., 101., 101., 101., 101.]],

       [[101., 101., 101., 101., 101.]],

       [[101., 101., 101., 101., 101.]],

       [[101., 101., 101., 101., 101.]],

       [[101., 101., 101., 101., 101.]]])

In [33]:
# substracting the array
a-1

array([[[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]]])

In [ ]:
# using the np.eye
# create the diagonal type this shit

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
# creating the empty spaces
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
# Random
import numpy as np
import random
random.choice((91,2,34,5,6,2,3,4))

34

In [18]:
# adding the range accordingly
random.randrange(1,10)

8

In [19]:
lis=[1,2,3,4,5,6,7]
lis

[1, 2, 3, 4, 5, 6, 7]

In [20]:
random.shuffle(lis)

In [21]:
random.uniform(7,10)

8.594960132645886

In [32]:
# random numbers related concepts in numpy
np.random.random_sample((5,10))

array([[0.41749352, 0.11515517, 0.31814297, 0.7950255 , 0.26622807,
        0.0022838 , 0.53396886, 0.14278467, 0.79094337, 0.51293436],
       [0.09185799, 0.75465242, 0.15824046, 0.1589937 , 0.76691729,
        0.17505961, 0.77687673, 0.97357235, 0.94114761, 0.54247993],
       [0.34321889, 0.07083255, 0.71502052, 0.19181331, 0.51074814,
        0.73541164, 0.0741674 , 0.42446861, 0.4920801 , 0.97832863],
       [0.68399218, 0.57821362, 0.38222729, 0.1120605 , 0.32198162,
        0.53091198, 0.61686957, 0.83991994, 0.77494551, 0.89355615],
       [0.42180826, 0.97856639, 0.59422273, 0.87613189, 0.53755947,
        0.25469507, 0.00627519, 0.62713258, 0.03658893, 0.07136757]])

In [33]:
np.random.rand(1)

array([0.058058])

In [38]:
random.randrange(1,10)

5

In [39]:
lis=[1,2,3,4,5,6,7]
lis

[1, 2, 3, 4, 5, 6, 7]

In [40]:
random.shuffle(lis)

In [41]:
lis

[1, 6, 4, 3, 5, 2, 7]

In [42]:
random.uniform(7,10)

9.977478048472214

In [43]:
np.array([])

array([], dtype=float64)

In [52]:
# using the random samples
np.random.random_sample()

0.4695314222620397

In [ ]:
#Standard normal distributions
np.random.rand(1,10)

array([[0.11213906, 0.86640143, 0.83291001, 0.43539178, 0.51102047,
        0.64219741, 0.86628795, 0.09893309, 0.29104998, 0.03014515]])

In [50]:
np.random.randn(2,10)

array([[ 0.74801483,  0.46872509, -0.22418011, -1.75986447,  0.35383235,
         0.24336297,  0.94642441,  0.87130814, -0.61383982,  0.35720795],
       [-0.4694019 , -0.97595533,  0.46881917,  2.09311309,  0.31717183,
         1.32709195, -0.53915301,  0.66589738,  1.1709534 ,  0.07612111]])

In [53]:
np.random.randint(1,5,size=(3,4))

array([[1, 4, 3, 3],
       [2, 3, 1, 1],
       [3, 1, 2, 2]], dtype=int32)

In [ ]:
#reshaping the array

arr =np.array(((3,4,4,3),(3,4,4,3),(3,4,4,3),(3,4,4,3)))
arr

array([[3, 4, 4, 3],
       [3, 4, 4, 3],
       [3, 4, 4, 3],
       [3, 4, 4, 3]])

In [15]:
arr.reshape(2,8)

array([[3, 4, 4, 3, 3, 4, 4, 3],
       [3, 4, 4, 3, 3, 4, 4, 3]])

In [16]:
arr.shape

(4, 4)

In [17]:
arr.ndim

2

In [22]:
#Changing the row of 12 size not lesser

myrowz=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
myrowz

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
myrowz.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
# Conditioning the arrraysmy
tr=np.random.randint(1,10,(5,6))
tr

array([[9, 4, 9, 4, 5, 9],
       [2, 1, 4, 1, 5, 7],
       [6, 1, 5, 2, 5, 1],
       [8, 5, 2, 3, 5, 9],
       [8, 3, 8, 3, 4, 8]], dtype=int32)

In [25]:
tr.shape

(5, 6)

In [26]:
tr.size

30

In [27]:
tr<4

array([[False, False, False, False, False, False],
       [ True,  True, False,  True, False, False],
       [False,  True, False,  True, False,  True],
       [False, False,  True,  True, False, False],
       [False,  True, False,  True, False, False]])

In [28]:
#Accessing all the elements in the arrays
tr[0]

array([9, 4, 9, 4, 5, 9], dtype=int32)

In [29]:
tr[0:10]

array([[9, 4, 9, 4, 5, 9],
       [2, 1, 4, 1, 5, 7],
       [6, 1, 5, 2, 5, 1],
       [8, 5, 2, 3, 5, 9],
       [8, 3, 8, 3, 4, 8]], dtype=int32)

In [32]:
tr[0:2]

array([[9, 4, 9, 4, 5, 9],
       [2, 1, 4, 1, 5, 7]], dtype=int32)

In [34]:
tr[0:2,[0,3]]

array([[9, 4],
       [2, 1]], dtype=int32)

In [36]:
# Slicin both row & coloumns
tr[0:4,1:4]

array([[4, 9, 4],
       [1, 4, 1],
       [1, 5, 2],
       [5, 2, 3]], dtype=int32)

In [38]:
tr

array([[9, 4, 9, 4, 5, 9],
       [2, 1, 4, 1, 5, 7],
       [6, 1, 5, 2, 5, 1],
       [8, 5, 2, 3, 5, 9],
       [8, 3, 8, 3, 4, 8]], dtype=int32)