In [7]:
import numpy as np

In [2]:
np.__version__

'2.2.1'

In [3]:
list=[1,2,3,4,5,6,7,7,8]
type(list)

list

In [10]:
ls=[1,2,3,4,5,6,7]
arrz=np.array(ls)
print(arrz)

[1 2 3 4 5 6 7]


In [11]:
type(arrz)

numpy.ndarray

In [12]:
# array can store homogenous data
ls=["swamy","money","bunny",1,2,3,4,5,6,7]
np.array(ls)

array(['swamy', 'money', 'bunny', '1', '2', '3', '4', '5', '6', '7'],
      dtype='<U21')

In [13]:
# adding the 2 dimension array
arr12=np.array([[1,2,3,4],[4,5,6,7]])
arr12

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [17]:
mns=np.array([[1,2,3,4,5],[21,22,23,24,25],[31,32,33,34,35],[41,42,43,44,45]])
mns

array([[ 1,  2,  3,  4,  5],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

In [21]:
mla=np.array([[1,2,3,4,5],[21,33,44,55,7],[1,2,3,4,5]])
type(mla)

numpy.ndarray

In [25]:
mtaz=np.array([[1,2,3,4,5],[22,33,44,55,66],[22,11,11,11,1]])
mtaz

array([[ 1,  2,  3,  4,  5],
       [22, 33, 44, 55, 66],
       [22, 11, 11, 11,  1]])

In [28]:
kyp=np.array([[1,2,3,4,5,6],[11,22,333,44,55,66],[11,22,11,11,1,1]])
kyp

array([[  1,   2,   3,   4,   5,   6],
       [ 11,  22, 333,  44,  55,  66],
       [ 11,  22,  11,  11,   1,   1]])

# creating the 3D array


In [30]:
ar3=np.array([
    [[1,2,3,4,5],[2,3,4,5,6],[11,22,33,44,55]],
    [[1,2,3,4,5],[22,11,22,44,55],[22,11,22,33,44]]
])
ar3

array([[[ 1,  2,  3,  4,  5],
        [ 2,  3,  4,  5,  6],
        [11, 22, 33, 44, 55]],

       [[ 1,  2,  3,  4,  5],
        [22, 11, 22, 44, 55],
        [22, 11, 22, 33, 44]]])