# Load data in from a file

In [1]:
import numpy as np

In [2]:
np.genfromtxt('gen.txt',delimiter=',')

array([[ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.]])

In [3]:
filedata=np.genfromtxt('gen.txt',delimiter=',')
filedata

array([[ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.]])

In [4]:
# changing the data type
filedata=np.genfromtxt('gen.txt',delimiter=',')
filedata.astype('int32')
filedata

array([[ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.]])

In [5]:
# changing the data type
filedata=np.genfromtxt('gen.txt',delimiter=',')
filedata=filedata.astype('int32')
filedata

array([[ 1, 13, 22,  3,  4,  5,  6,  7,  7,  8, 99, 11, 33, 44, 66, 66,
        88],
       [ 1, 13, 22,  3,  4,  5,  6,  7,  7,  8, 99, 11, 33, 44, 66, 66,
        88],
       [ 1, 13, 22,  3,  4,  5,  6,  7,  7,  8, 99, 11, 33, 44, 66, 66,
        88],
       [ 1, 13, 22,  3,  4,  5,  6,  7,  7,  8, 99, 11, 33, 44, 66, 66,
        88],
       [ 1, 13, 22,  3,  4,  5,  6,  7,  7,  8, 99, 11, 33, 44, 66, 66,
        88]], dtype=int32)