# Load data in from a file

In [2]:
import numpy as np

In [3]:
np.genfromtxt('gen.txt',delimiter=',')

array([[ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.]])

In [4]:
filedata=np.genfromtxt('gen.txt',delimiter=',')
filedata

array([[ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.]])

In [5]:
# changing the data type
filedata=np.genfromtxt('gen.txt',delimiter=',')
filedata.astype('int32')
filedata

array([[ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.],
       [ 1., 13., 22.,  3.,  4.,  5.,  6.,  7.,  7.,  8., 99., 11., 33.,
        44., 66., 66., 88.]])

In [6]:
# changing the data type
filedata=np.genfromtxt('gen.txt',delimiter=',')
filedata=filedata.astype('int32')
filedata

array([[ 1, 13, 22,  3,  4,  5,  6,  7,  7,  8, 99, 11, 33, 44, 66, 66,
        88],
       [ 1, 13, 22,  3,  4,  5,  6,  7,  7,  8, 99, 11, 33, 44, 66, 66,
        88],
       [ 1, 13, 22,  3,  4,  5,  6,  7,  7,  8, 99, 11, 33, 44, 66, 66,
        88],
       [ 1, 13, 22,  3,  4,  5,  6,  7,  7,  8, 99, 11, 33, 44, 66, 66,
        88],
       [ 1, 13, 22,  3,  4,  5,  6,  7,  7,  8, 99, 11, 33, 44, 66, 66,
        88]], dtype=int32)

## Advance boolean & masking


In [7]:
filedata >50

array([[False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False,  True,  True,  True]])

In [8]:
filedata[filedata>50]

array([99, 66, 66, 88, 99, 66, 66, 88, 99, 66, 66, 88, 99, 66, 66, 88, 99,
       66, 66, 88], dtype=int32)

In [12]:
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [13]:
((filedata>50)&(filedata<100))

array([[False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False,  True,  True,  True]])