# Initializing Different types of Arrays


In [1]:
import numpy as np

In [3]:
#All the zeros matrix
np.zeros(4)

array([0., 0., 0., 0.])

In [5]:
# 2 dimensional arrays
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# 3 dimensional arrays
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [7]:
# 4 dimensional arrays
np.zeros((2,3,3,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [10]:
#all matrix one
np.ones((2,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [11]:
#Any other number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [13]:
  # Any other number (full_like)
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
np.full_like(a,4)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [14]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [15]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.94139916, 0.16933029],
       [0.92447855, 0.11700345],
       [0.16237403, 0.12507038],
       [0.68955655, 0.58677023]])

In [16]:
# random example 2
np.random.random_sample(a.shape)

array([[0.64624805, 0.22146438, 0.51428176, 0.76818615, 0.27891637,
        0.06549567, 0.71447639],
       [0.77535153, 0.77005779, 0.37160959, 0.17037832, 0.74628067,
        0.8034495 , 0.13413817]])

In [19]:
# Random Integer values
np.random.randint(7,size=(3,3))

array([[3, 6, 4],
       [6, 5, 5],
       [3, 6, 6]], dtype=int32)

In [ ]:
# Random Integer values (number keep changing)
np.random.randint(4,7,size=(3,2))

array([[5, 5],
       [6, 5],
       [5, 5]], dtype=int32)

In [23]:
# trying some negative numbers
np.random.randint(-4,8,size=(3,3))

array([[ 5,  2,  7],
       [ 3,  6, -3],
       [ 2,  3,  1]], dtype=int32)

In [27]:
# Indentifying the matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
arr =np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]]
