# Solving the problem of the numpy


In [4]:
import numpy as np
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:-1,1:-1]=z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# be carefull copying array (regular problem)
a=np.array([1,2,3])
print(a)
b=a
b[0]=100
print(a)

[1 2 3]
[100   2   3]


In [8]:
# Right way to copy array
a=np.array([1,2,3])
print(a)
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[1 2 3]
[100   2   3]


# Mathematics


In [4]:
na=np.array([1,2,3,4,5])
print(na)

[1 2 3 4 5]


In [6]:
na+2

array([3, 4, 5, 6, 7])

In [7]:
na-2

array([-1,  0,  1,  2,  3])

In [8]:
na*2

array([ 2,  4,  6,  8, 10])

In [9]:
na/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [10]:
nb=np.array([1,0,0,2,1])
na+nb

array([2, 2, 3, 6, 6])

In [11]:
na ** 2


array([ 1,  4,  9, 16, 25])

In [12]:
# taking sin
np.sin(na)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

# linear Algebra


In [15]:
am=np.ones((2,3))
print(am)
an=np.full((3,2),2)
print(an)
am * an

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [16]:
am=np.ones((2,3))
print(am)
an=np.full((3,2),2)
print(an)
np.matmul(am,an)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# find the determinant
ac=np.identity(3)
np.linalg.det(ac)

np.float64(1.0)