# Statistics


In [1]:
# statistcs mean s mean ,meadian min ,max etc

In [2]:
import numpy as np

In [6]:
stats= np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.min(stats,axis=0)

array([1, 2, 3])

In [8]:
np.max(stats)

np.int64(6)

In [10]:
np.sum(stats,axis=0)

array([5, 7, 9])