In [1]:
import numpy as np

In [ ]:
a=np.array([
    [1,23,33,44],[2,2,2,3],[3,3,3,4],[5,5,55,7]
    ])
print(a)

[[ 1 23 33 44]
 [ 2  2  2  3]
 [ 3  3  3  4]
 [ 5  5 55  7]]


In [5]:
a.ndim

2

In [6]:
print (a.ndim)

2


In [7]:
#getting the shape
a.shape

(4, 4)

In [8]:
a.dtype

dtype('int64')

In [9]:
a.itemsize

8

In [10]:
a.nbytes

128