# Accessing / Changing the specififc elemetns rows & coloumns 

In [1]:
import numpy as np

In [6]:
ab=np.array([[1,2,3,4,5,6,6,7],[10,22,33,44,66,77,88,99],
             [1,2,3,4,5,6,6,7],[10,22,33,44,66,77,88,99]])
print(ab)

[[ 1  2  3  4  5  6  6  7]
 [10 22 33 44 66 77 88 99]
 [ 1  2  3  4  5  6  6  7]
 [10 22 33 44 66 77 88 99]]


In [7]:
ab.ndim

2