In [1]:
# Accessing, Changing Specific elements, Rows, Coloumns etc (slicing)

In [1]:
import numpy as np


In [2]:
# creating 2x7 array in it
a=np.array([[1,23,45,6,8],[1,2,3,4,5]])
print(a)

[[ 1 23 45  6  8]
 [ 1  2  3  4  5]]


In [3]:
# getting the specific element in the row a[r,c]
a[1,3]

np.int64(4)

In [4]:
a[0,2]

np.int64(45)

In [5]:
# get the specific row in python
a[0,:]

array([ 1, 23, 45,  6,  8])

In [6]:
# get the specific coloumn in python
a[:,0]

array([1, 1])

In [7]:
a[:,1]

array([23,  2])

In [8]:
# Getting little fancy elements
a[0,1:-1:2]

array([23,  6])

In [11]:
#updated the code
a[1,2] =20
print(a)


[[ 1 23 45  6  8]
 [ 1  2 20  4  5]]


In [12]:
# 3d array example
b= np.array([[[1,2],[2,2],[3,2],[4,2],[5,2],[7,2]]])
print(b)

[[[1 2]
  [2 2]
  [3 2]
  [4 2]
  [5 2]
  [7 2]]]


In [13]:
# getting the specific element in array
b[0,1,2]

IndexError: index 2 is out of bounds for axis 2 with size 2

In [14]:
#getting the specific element
b[0,1]

array([2, 2])