In [1]:
#My first numpy code is up here


In [2]:
# my numpy code


In [4]:
import numpy as np


In [4]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
#creating two / three dimensional arrays in Numpy
mn= np.array([[1,2,3],[1,2,3],[2,2,3]])
print(mn)



[[1 2 3]
 [1 2 3]
 [2 2 3]]


In [11]:
# getting the dimension of the  array
mn.ndim

2

In [12]:
a.shape


(4,)

In [13]:
# Gets the shape
mn.shape

(3, 3)

In [14]:
# gets the datatype
a.dtype

dtype('int64')

In [15]:
#gets the size
mn.itemsize

8

In [16]:
mn.size * mn.itemsize

72

In [17]:
#gets the total size
mn.nbytes

72