# Practise


In [3]:
import numpy as np

In [4]:
az= np.array([[1,2,3,4,6,7],[2,3,4,5,6,8]])
print(az)

[[1 2 3 4 6 7]
 [2 3 4 5 6 8]]


In [10]:
#  getting specific elements (r,c)
az[0,4]

np.int64(6)

In [12]:
# getting the specific row
az[1,:]

array([2, 3, 4, 5, 6, 8])

In [14]:
# getting specific coloumn
az[:,5]

array([7, 8])

In [21]:
# getting more complex [start index : end index : step size]
az[0,1:6:3]

array([2, 6])

In [18]:
print (az)

[[1 2 3 4 6 7]
 [2 3 4 5 6 8]]


In [22]:
# updating the elements
az[1,3]=8
print(az)

[[1 2 3 4 6 7]
 [2 3 4 8 6 8]]


In [23]:
# updated the row elements
az[:,3]=[1,2]
print(az)

[[1 2 3 1 6 7]
 [2 3 4 2 6 8]]


In [4]:
# 3D Array 
b=np.array([[[1,2],[3,4]],[[5,6],[6,7]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


In [5]:
#Getting the specific elements
b[:,1,:]

array([[3, 4],
       [6, 7]])

In [7]:
#replace
b[:,1,:] = [[9,9],[8,9]]

In [8]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 9]]]
